### ISSUE TITLE
[Meta] Move to orgs

### ISSUE THREAD

**Issue by noaione** [noaione/tosho-mango#35]
https://github.com/tosho-dev

Will be used for some of the other stuff I develop too.

To-do list:
- [ ] Move to orgs
- [ ] Adjust CI
- [ ] Create publisher/orgs account in Crates.io
- [ ] Change all the links
